### ISSUE TITLE
装备的Stats对象对key做了汉化是出于什么原因

### ISSUE THREAD

**Issue by Luc41** [thewakingsands/cafemaker#2]
e.g. https://cafemaker.wakingsands.com/item/29050?columns=Stats

返回：{"Stats":{"\u529b\u91cf":{"ID":1,"NQ":634},"\u66b4\u51fb":{"ID":27,"NQ":498},"\u76f4\u51fb":{"ID":22,"NQ":349},"\u8010\u529b":{"ID":3,"NQ":707}}}

这种情况对于使用xivapi的代码没有办法直接复用，我的理解key不做变动，前端自行处理应该是更好的选择吧。

**Comment by oott123** [comment]
Stat 读的是 BasicParam 表，cafemaker 修改了默认语言为中文，所以做预处理的时候就变成那样了

听起来是个 bug，想修的话可以 pr

**Comment by Luc41** [comment]
了解了，既然是feature那我换一种实现吧(￣∇￣)
