### ISSUE TITLE
/patchlist outdated

### ISSUE THREAD

**Issue by Luc41** [thewakingsands/cafemaker#3]
目前通过/patchlist获得的版本号还停留在5.18
这部分数据是不再更新了么

**Comment by oott123** [comment]
这个不属于例行维护的数据范围内，想更新的话可以 pr

https://github.com/thewakingsands/cafemaker-web/blob/cn/src/Service/GamePatch/resources/patchlist.json

**Comment by TundraWork** [comment]
@oott123 I think it's better to provide a JSON API of our internal patchlist management system ( c*****.wakingsands.com ), since XIVAPI's /patchlist endpoint do not provide any actual information other than our data, including their upstream.

**Comment by oott123** [comment]
> I think it's better to provide a JSON API of our internal patchlist management system 

/patchlist endpoint of xivapi is used by many data sources like items to determine which patch that the specific item added into the game.

Maybe we should have some pipeline to migrate both data into xivapi, but that's a long term plan.

For now, developers can go though xivapi for that information and use cafemaker only for translations, just like what teamcraft does.

**Comment by oott123** [comment]
已经同步 6.0 代码
