### ISSUE TITLE
6.0在search中搜索不到乐谱配方了

### ISSUE THREAD

**Issue by Paomiantong** [thewakingsands/cafemaker#7]
`https://cafemaker.wakingsands.com/search?indexes=Recipe&string=%E4%B9%90%E8%B0%B1`

`{
  "Pagination": {
    "Page": 1,
    "PageNext": null,
    "PagePrev": null,
    "PageTotal": 1,
    "Results": 4,
    "ResultsPerPage": 100,
    "ResultsTotal": 4
  },
  "Results": [
    {
      "ID": 1994,
      "Icon": "/i/052000/052512.png",
      "Name": "庄园乐谱架",
      "Url": "/Recipe/1994",
      "UrlType": "Recipe",
      "_": "recipe",
      "_Score": "11.248562"
    },
    {
      "ID": 2864,
      "Icon": "/i/025000/025955.png",
      "Name": "1级空白管弦乐琴乐谱",
      "Url": "/Recipe/2864",
      "UrlType": "Recipe",
      "_": "recipe",
      "_Score": "6.8650723"
    },
    {
      "ID": 2865,
      "Icon": "/i/025000/025955.png",
      "Name": "2级空白管弦乐琴乐谱",
      "Url": "/Recipe/2865",
      "UrlType": "Recipe",
      "_": "recipe",
      "_Score": "6.8650723"
    },
    {
      "ID": 2866,
      "Icon": "/i/025000/025955.png",
      "Name": "3级空白管弦乐琴乐谱",
      "Url": "/Recipe/2866",
      "UrlType": "Recipe",
      "_": "recipe",
      "_Score": "6.8650723"
    }
  ],
  "SpeedMs": 4
}`

**Comment by oott123** [comment]
收到，调查中

**Comment by oott123** [comment]
上游问题，CM已修复，同时已提交上游补丁
