### ISSUE TITLE
古典风格装备Icon出错

### ISSUE THREAD

**Issue by Paomiantong** [thewakingsands/cafemaker#8]
古典风格拳斗士面具的图标和绿色绣球花的图标是一样的
古典风格拳斗士面具：https://cafemaker.wakingsands.com/i/041000/041880.png
绣球花：https://cafemaker.wakingsands.com/i/054000/054305.png

还有其他的580装备无法访问
例如古典风格拳斗士兜甲：https://cafemaker.wakingsands.com/i/042000/042791.png

**Comment by oott123** [comment]
图标还没更新完，预计大概今晚搞定

**Comment by oott123** [comment]
已更新，可能需要等待 24 小时才能使 CDN 缓存生效，如还未生效请继续 open issue
感谢反馈
